Code for the first task. Class implementation-priority queue
kekafon/DBMS pull request #5
Opened 2020-09-12 10:01 UTC by kekafon

Попробовал реализовать класс, с заданной структурой данных, в моем случаем - очередь с приоритетом. Сделал меню, для демонстрации методов

2020-09-16 13:01 UTC, Const-Phi requested changes
Не касаясь пока самой реализации структуры, помимо уже указанных замечаний, есть ещё два, носящих более-менее глобальный характер:

1. Подразумевается, что данная коллекция (как реализация структуры данных) позволяет хранить объекты _любого_ типа. _Так ли это?_
1. Сквозь формат `Jupiter`-а очень сложно продираться, не работая в нём (особенно при помощи текстового представления `GitHub`-а). _Существует ли альтернатива публиковать только код вида `*.py`, а не `*.ipynb`?_ На сколько мне видится, единственный выигрыш в последнем &ndash; наличие _как бы_ `test case`-ов.

2020-09-16 13:01 UTC, Const-Phi commented on .ipynb_checkpoints/task1-checkpoint.ipynb
> +    "                push_elements(queue)\n",
Я бы несколько переписал этот код, повысив повторное использование посредством повышения уровня абстракции &ndash; использование [&lambda;-функций](https://realpython.com/python-lambda/) и [функции высшего порядка](https://ru.wikipedia.org/wiki/Функция_высшего_порядка) нам в помощь. Как образец приведу следующий отрывок кода
```python
def wrapper(queue, target):
  if queue == 'None':
    print('\\nОчерь не создана! Создайте очередь с приоритетом.')
  else:
    target(queue)

def print_queue(queue):
  queue.print()

def user_interface():
    # ...

    if number == 1:
        queue = create_queue()
    elif number == 2:
        wrapper(queue, push_element)  
    elif number == 3:
        wrapper(queue, pop_element) 
    elif number == 4:
        wrapper(queue, print_queue)
    elif number == 5:
        wrapper(queue, replace_element)
    elif number == 6:
        wrapper(queue, push_elements)

    # ...
```

2020-09-16 13:01 UTC, Const-Phi commented on .ipynb_checkpoints/task1-checkpoint.ipynb
> +    "            number = int(input('Введите номер пункта меню: '))\n",
Кажется, что здесь можно тоже (_творчески переосмыслив_) использовать функцию `enter_element(text_input)`.

2020-09-16 13:01 UTC, Const-Phi commented on .ipynb_checkpoints/task1-checkpoint.ipynb
> +    "    values = get_random_values(size)\n",
Кажется, что стоит разнести этот пункт меню на два &ndash; &laquo;Создать _пустую_ очередь&raquo; и &laquo;Создать очередь, _заполненную псевдослучайными значениями_&raquo;.

**UPD**
Как вариант второй (под)пункт можно свести к &laquo;Заполнить очередь  псевдослучайными значениями&raquo;, с созданием соответствующей функции и использования `wrapper`-а по этому знаменательному поводу.

2020-09-16 13:26 UTC, kekafon commented on .ipynb_checkpoints/task1-checkpoint.ipynb
> +    "                push_elements(queue)\n",
Пока что в программу можно вводить только инты, если реализовать метод для ввода стрингов, то тоже будет работать. В случаем со стрингами, приоритет по получит строка с Первой буквой по алфавиту. Объекты вводить не пробовал, и нужно ли это вообще?
По поводу .py, скидывать в этом формате.
Все комментарии понял, попробую сделать )

2020-09-16 13:40 UTC, kekafon commented on .ipynb_checkpoints/task1-checkpoint.ipynb
> +    "                push_elements(queue)\n",
Вопрос такой: Марина Алексеевна сказала не делать никаких выводов в консоль в классе. Придерживаться этого? стоит менять:
`class PriorityQueue():
    def print(self):
         print(self.heap)
`

2020-09-16 14:42 UTC, kekafon commented
Нужно ли добавлять метод для добавления строки в очередь?

2020-09-22 17:39 UTC, kekafon commented on .ipynb_checkpoints/task1-checkpoint.ipynb
> +    "                push_elements(queue)\n",
В данной структуре данных могут быть либо инты, либо стринги, вместе быть не могут, так как их не получится сравнивать между собой. НО можно реализовать структуру таким образом, что она будет хранить числа, как строку и строки, как строки. Например будет выглядеть так ['1', '2', '3', 'Alex', 'Dima']. Наивысший приоритет у наименьшего числа, затем идут строки, где наивысший приоритет определяется по алфавиту.

2020-09-29 11:00 UTC, Const-Phi commented on .ipynb_checkpoints/task1-checkpoint.ipynb
> +    "                push_elements(queue)\n",
> Вопрос такой: Марина Алексеевна сказала не делать никаких выводов в консоль в классе. Придерживаться этого? стоит менять:
     ```py
     class PriorityQueue(): def print(self): print(self.heap)
     ```
Короткий ответ следующий. Так как делаем &laquo;по аджайлу&raquo;, то имеет смысл обеспечить хоть какой-то способ вывода информации о внутреннем состоянии коллекции. Если это можно сделать малой кровью и хорошо, то делаем хорошо. Теоретически я бы добавил
```py
    def __str__(self):
    # что-то делаем для строкового представления коллекции
```

> В данной структуре данных могут быть либо инты, либо стринги, вместе быть не могут, так как их не получится сравнивать между собой. [...] 

И слава Богу! Так и должно быть!

> НО можно реализовать структуру таким образом, что она будет хранить числа, как строку и строки, как строки. Например будет выглядеть так ['1', '2', '3', 'Alex', 'Dima']. Наивысший приоритет у наименьшего числа, затем идут строки, где наивысший приоритет определяется по алфавиту.

Нет, подразумевалось, что хранится будут данные одного типа, но структуре всё равно какого &ndash; числа, строки, объекты, други коллекции etc.

2021-01-26 08:54 UTC, merged